version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/fastapi
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"

volumes:
  postgres_data:
