services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/c3techie-fastapi-kit
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=c3techie-fastapi-kit
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: fastapi_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
