"""Add admin model

Revision ID: be08e6172a67
Revises: 0a107e81f8ae
Create Date: 2025-06-06 22:27:24.185273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # For PostgreSQL-specific types (JSONB, UUID, etc.)
from sqlalchemy.sql import text  # For raw SQL queries
from sqlalchemy.dialects import postgresql

# --- Revision identifiers ---
revision = 'be08e6172a67'
down_revision = '0a107e81f8ae'
branch_labels = None
depends_on = None

def upgrade():
    """Upgrade database schema to this revision."""
    bind = op.get_bind()  # Optional: Get the DB connection for raw SQL
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_assigned_at', 'admins', ['assigned_at'], unique=False)
    op.create_index('idx_admin_user_id_active', 'admins', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    """Downgrade database schema to the previous revision."""
    bind = op.get_bind()  # Optional: Get the DB connection for raw SQL
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index('idx_admin_user_id_active', table_name='admins')
    op.drop_index('idx_admin_assigned_at', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###